import NavBar from '@/components/NavBar';
import MobileNavBar from '@/components/MobileNavBar';
import UserSync from '@/components/UserSync'
import { type Metadata } from 'next'
import {
  ClerkProvider
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'FitStreak',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserSync />
          <NavBar />
          <main className="min-h-screen pb-16">{children}</main> {/* padding-bottom for mobile nav */}
          <MobileNavBar />
        </body>
      </html>
    </ClerkProvider>
  )
}